version: 2.1

orbs:
  codeclimate:    sue445/codeclimate@volatile
  github-release: izumin5210/github-release@0.1.1
  go-module:      timakin/go-module@0.3.0
  heroku:         circleci/heroku@volatile
  slack:          circleci/slack@volatile

executors:
  golang:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/sue445/gitpanda
    environment:
      GO111MODULE: "on"

jobs:
  test:
    executor: golang

    environment:
      CC_TEST_REPORTER_ID: 3189062605b5e7e7ea3aa51b854c1912cfe29dcee0049e1ecdbc3f57a7a27327
      TEST_ARGS: "-coverprofile c.out"

    steps:
      - &attach_workspace
        attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - &restore_cache
        restore_cache:
          key: go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
      - codeclimate/with-cc-test-reporter:
          steps:
            - run: make test
            - run: make testrace
      - slack/status

  golint:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: go get -u golang.org/x/lint/golint
      - run: make lint
      - slack/status

  go-vet:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: make vet
      - slack/status

  gofmt:
    executor: golang

    steps:
      - *attach_workspace
      - *restore_cache
      - run: "! gofmt -d . | grep '^'"
      - slack/status

  gox:
    executor: golang

    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: rm bin/.keep
      - run: make gox_with_zip
      - persist_to_workspace:
          root: /go/src/github.com/sue445/gitpanda
          paths:
            - .
      - slack/status

workflows:
  build-and-deploy:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

      - golint:
          requires:
            - go-module/download

      - go-vet:
          requires:
            - go-module/download

      - gofmt:
          requires:
            - go-module/download

      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - test
            - golint
            - go-vet
            - gofmt
          filters:
            branches:
              only: master
          post-deploy:
            - slack/status

  release:
    jobs:
      - gox:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(\.[a-z]+[0-9]*)?$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: false
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - github-release/create:
          executor: golang
          path: ./bin/
          prerelease: true
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+\.[a-z]+[0-9]*$/
